---
# tasks file for openvas
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install repository
  package:
    name: "{{ openvas_release }}"
    state: present

- name: disable selinux
  selinux:
    state: disabled
  notify:
    - reboot

- name: flush handlers
  meta: flush_handlers

- name: install requirements (package)
  package:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ openvas_requirements }}"
  when:
    - item.type == "package"

- name: install requirements (pip)
  pip:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ openvas_requirements }}"
  when:
    - item.type == "pip"

- name: install software
  package:
    name: openvas
    state: present
  notify:
    - setup software

- name: flush handlers
  meta: flush_handlers

- name: check setup software
  async_status:
    jid: "{{ setup_software.ansible_job_id }}"
  register: check_setup_software
  until: check_setup_software.finished
  retries: 180
  delay: 10
  when:
    - setup_software is defined

- name: enable software
  service:
    name: openvas-manager
    state: started
    enabled: yes
