---
# tasks file for openvas
- name: install requirements (package)
  package:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ openvas_requirements }}"
  when:
    - item.type == "package"

- name: install requirements (pip)
  pip:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ openvas_requirements }}"
  when:
    - item.type == "pip"

- name: install repository (yum/dnf)
  package:
    name: "{{ openvas_release[ansible_distribution] }}"
    state: present
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: install repository key (apt)
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: FFBD5D0A4520AFA9
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: install repository key (yum/dnf)
  rpm_key:
    key: https://www.atomicorp.com/RPM-GPG-KEY.art.txt
    state: present
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: install repository (apt)
  apt_repository:
    repo: "{{ openvas_release[ansible_distribution] }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: disable selinux
  selinux:
    state: disabled
  notify:
    - reboot
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: flush handlers
  meta: flush_handlers

- name: install openvas (package)
  package:
    name: "{{ openvas_packages[ansible_distribution]
          | default(openvas_packages['default']) }}"
    state: "{{ openvas_package_state }}"
  notify:
    - setup openvas

- name: flush handlers
  meta: flush_handlers

- name: enable openvas
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
  with_items:
    - openvas-manager
    - gsad
