---
# tasks file for openvas
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install repository (rpm)
  package:
    name: "{{ openvas_release }}"
    state: present
  when:
   - ansible_pkg_mgr == "rpm"

- name: install repository (apt)
  apt_repository:
    repo: "{{ openvas_release }}"
    state: present
  when:
    - ansible_pkg_mgr == apt

- name: disable selinux
  selinux:
    state: disabled
  notify:
    - reboot
  when:
    - ansible_selinux.state is defined

- name: flush handlers
  meta: flush_handlers

- name: install requirements (package)
  package:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ openvas_requirements }}"
  when:
    - item.type == "package"

- name: install requirements (pip)
  pip:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ openvas_requirements }}"
  when:
    - item.type == "pip"

- name: install software
  package:
    name: openvas
    state: present
  notify:
    - setup software

- name: flush handlers
  meta: flush_handlers

- name: enable software
  service:
    name: openvas-manager
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
