---
# tasks file for openvas
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install requirements (package)
  "{{ ansible_pkg_mgr }}:
    name: "{{ item.name }}"
    state: present
    repository: "{{ openvas_repository | default(omit) }}"
  with_items:
    - "{{ openvas_requirements }}"
  when:
    - item.type == "package"

- name: install requirements (pip)
  pip:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ openvas_requirements }}"
  when:
    - item.type == "pip"

- name: install repository (yum/dnf)
  package:
    name: "{{ openvas_release }}"
    state: present
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: install repository key (apt)
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: FFBD5D0A4520AFA9
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: install repository key (yum/dnf)
  rpm_key:
    key: https://www.atomicorp.com/RPM-GPG-KEY.art.txt
    state: present
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: install repository (apt)
  apt_repository:
    repo: "{{ openvas_release }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: disable selinux
  selinux:
    state: disabled
  notify:
    - reboot
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: flush handlers
  meta: flush_handlers

- name: install software
  package:
    name: openvas
    state: present
  notify:
    - setup software

- name: flush handlers
  meta: flush_handlers

- name: enable software
  service:
    name: openvas-manager
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
