---
# handlers file for openvas
- name: reboot
  shell: (sleep "{{ openvas_reboot_delay }}" && shutdown -r now "ansible-role-update" &)
  async: 1
  poll: 0
  ignore_errors: yes
  when:
    - ansible_virtualization_type != "docker"
  notify:
    - wait for the machine to be up

- name: wait for the machine to be up
  wait_for_connection:
    delay: "{{ openvas_up_delay }}"

- name: setup software
  expect:
    command: openvas-setup
    timeout: 1800
    responses:
      'Downloader \[Default: rsync\]': rsync
      'Allow connections from any IP\? \[Default: yes\]': "yes"
      'Enter administrator username \[Default: admin\]': "{{ openvas_administrator_username }}"
      'Password:': "{{ openvas_administrator_password }}"
      'Verify Administrator Password:': "{{ openvas_administrator_password }}"
      'Enter Administrator Password:': "{{ openvas_administrator_password }}"
  async: 1800
  poll: 0
  register: setup_software
  when:
    - ansible_virtualization_type != "docker"
  notify:
    - check setup software

- name: check setup software
  async_status:
    jid: "{{ setup_software.ansible_job_id }}"
  register: check_setup_software
  until: check_setup_software.finished
  retries: 180
  delay: 10
