---
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  vars:
    redis_ignore_docker: no
    selinux_ignore_docker: no
    reboot_ignore_docker: no

  roles:
    - robertdebock.bootstrap
    - robertdebock.buildtools
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.redis
    - ansible-role-openvas
